# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(100,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsC <- function(N, thin) {
    .Call('_SA24204135_gibbsC', PACKAGE = 'SA24204135', N, thin)
}

#' @title Use three inputs to predict response using Rcpp.
#' @description The prediction model is described in http://www.babelgraph.org/wp/?p=358.
#' @param age the first predictor (numeric)
#' @param female the second predictor (logical)
#' @param ily the third predictor (logical)
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' data(data)
#' attach(data)
#' res <- vaccC(age,female,ily)
#' }
#' @export
vaccC <- function(age, female, ily) {
    .Call('_SA24204135_vaccC', PACKAGE = 'SA24204135', age, female, ily)
}

#' @name qr_decomposition
#' @title QR Decomposition
#' @description Compute the QR decomposition of a matrix A
#' @param A A numeric matrix
#' @return A list containing matrices Q and R
#' @export
qr_decomposition <- function(A) {
    .Call('_SA24204135_qr_decomposition', PACKAGE = 'SA24204135', A)
}

#' @name monte_carlo_pi
#' @title Monte Carlo Estimation of Pi
#' @description Use Monte Carlo simulation to estimate the value of Pi
#' @param n An integer specifying the number of random points to generate
#' @return An estimate of Pi
#' @export
monte_carlo_pi <- function(n) {
    .Call('_SA24204135_monte_carlo_pi', PACKAGE = 'SA24204135', n)
}

